name: Master

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        dotnet-version: ['2.2.108', '3.0.100']
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      NUGET_XMLDOC_MODE: skip
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1
    - name: Setup .NET Core 2.2.108
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '2.2.108'
    - name: Setup .NET Core ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: Test
      run: dotnet test -c Release ./Mamemaki.HolidayJp.Test/Mamemaki.HolidayJp.Test.csproj
